import React from 'react';
import { useTranslation } from 'react-i18next';

function TermsCondition() {
    const { t } = useTranslation();
    return (
        <div>

            <div className='container py-5'>
                <h1>Terms & Condition Policy</h1>

                <p> <strong>PLEASE READ THESE TERMS OF USE CAREFULLY. BY USING THE PLATFORM, YOU AGREE TO BE BOUND BY ALL OF THE BELOW TERMS AND CONDITIONS AND THE PRIVACY POLICY.</strong></p>
                <p><strong>THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARY GUIDELINES AND DIGITAL MEDIA ETHICS CODE) RULES, 2021 THAT REQUIRES PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND USER AGREEMENT FOR ACCESS OR USAGE OF THE APP/ Web.</strong></p>

                <ul><li>The websites (https://www.satim.com)  is owned and operated by satim, a company incorporated in India under the Companies Act, 2013 and having its registered office at #1/606A vaishali ghaziabad up 201010 and includes any of our affiliates, associates, assignees or successors-in-interest as determined by us at our sole discretion and without requiring any prior notice or intimation to you (" Company" , " we " or " us" or " our" ). The Platform aims to digitize temples and other religious experiences for its users, provide astrological services and other related services ("Services").
                    This Privacy Policy ("Privacy Policy") sets out the privacy practices of the Company with respect to the entire content of the Platform.
                    For the purposes of this Privacy Policy, the words "us", "we", and "our" refer to the Company and all references to "you" , "your" or "user", as applicable means the person who accesses, uses and/or participates in the Platform in any manner or capacity.
                    By using or visiting the Platform, you signify your agreement to these Terms of Use and the Privacy Policy.
                </li></ul>

                <p> These Terms of Use are an electronic record as per the Information Technology Act, 2000 (as amended/re-enacted) and rules thereunder (“IT Act") and is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics code) Rules, 2021, which mandates the publishing of rules and regulations, privacy policy and terms and conditions for access or usage of any application or website. This electronic record is generated by a computer system and does not require any physical or digital signature. In addition, some of the Services may be subject to additional terms and conditions specified by us from time to time; your use of such solution is subject to those additional terms and conditions, which are incorporated into these Terms of Use by reference.</p>

                <h2>1)	OVERVIEW OF THE SERVICES</h2>
                <p>We are, among other things, engaged in the business of digitizing temples and other religious experiences, providing astrological services and other related services ('Services") to our users. Delivered in the premises and you can also order God's Prasad and items online on our website.</p>

                <h2>2)	ACCEPTANCE OF TERMS</h2>

                <p>By downloading and/or by registering or signing up for these Services, or otherwise having access to, receiving, and/or using the Platform, you acknowledge to have read, understood and consented to be governed and bound by these Terms of Use and the Privacy Policy. If you do not accept or agree to any part of these Terms of Use or the Privacy Policy, your usage of the Services will be terminated.</p>

                <h2>3)	ACCESS</h2>

                <p>ubject to these Terms of Use, we may offer to provide you with Services selected by you, solely for your own use, and not for the use or benefit of any third party. Services shall include, but not be limited to, any services we perform for you, any hardware offered by us, or any widgets that you download from the Platform. In case of any descrepancy in the Services, you must bring the same to our notice in writing, within a period of 7 (seven) days from date of performance of the Services, failing which the Services shall be deemed accepted, fulfilled and satisfactorily completed.</p>
                <p>You agree not to circumvent, disable or otherwise interfere with security-related features of the Platform or features that prevent or restrict use or copying of any restricted information.</p>

                <h2>4)	REGISTRATION AND ELIGIBILITY</h2>

                <p>Only persons who can form legally binding contracts under the Indian Contract Act, 1872 may access the Platform and avail our Services. Persons who are ‘incompetent to contract’ within the meaning of the Indian Contract Act, 1872 including without limitation, un-discharged insolvents, are not eligible to avail our Services. If you are a minor i.e., under the age of 18 (eighteen) years, you cannot register and/or avail our Services. We reserve the right to refuse to provide you with access to the Services if it is brought to our notice or if it is discovered that you are incompetent to contract. You represent and warrant to us that you are of legal age to form a binding contract and are not a person barred from availing the Services under applicable laws.</p>
                <p>You may, at your sole discretion, log into the application using your phone number ("Login Details").</p>
                <p>Notwithstanding anything contained herein, you shall not:</p>
                <p>Provide any false personal information to us (including false/fraudulent Login Details) or create any account for anyone other than yourself without such person's explicit permission; or</p>
                <p>use the Login Details of another person with the intent to impersonate that person.</p>

                <h2>5)	YOUR RESPONSIBILITIES</h2>

                <p>By using the Platform, you represent and warrant that:</p>

                <ul>
                    <li>You have fully read and understood the Terms of Use and Privacy Policy and consent to them;</li>
                    <li>You will ensure that your use of the Platform and/or Services will not violate any applicable law or regulation;</li>
                    <li>You have no rights in, or to, the Platform or the technology used or supported by the Platform or any of the Services, other than the right to use each of them in accordance with these Terms of Use;</li>
                    <li>You will not use the Platform or the Services in any manner inconsistent with these Terms of Use or Privacy Policy;</li>
                    <li>You will not resell or make any commercial use of the Services or use the Services in any way that is unlawful, for any unlawful purpose, or in a manner that your use harms us, the Platform, or any other person or entity, as determined in our sole discretion, or act fraudulently or maliciously;</li>
                    <li>You will not decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any hardware, or source code or underlying ideas or algorithms of any part of the Service (including without limitation any application or widget), except to the limited extent applicable laws specifically prohibit such restriction</li>
                    <li>You will not transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Platform or any connected network, or otherwise damage, disable, overburden, impair or compromise the Platform, our systems or security or interfere with any person or entity's use or enjoyment of the Platform;</li>

                    <li>6.1.8. you will not post, publish or transmit any content or messages that 1. are false, misleading, defamatory, harmful, threatening, abusive or constitute harassment (2) promote racism, entail hateful slurs or promote hateful behavior, associate with hate groups or any violence towards others including terrorism or self-harm or suicide or harm against any individual or group or religion or caste, (3) infringe another's rights including any intellectual property rights or copyright or trademark, violate or encourage any conduct that would violate any applicable law or regulation or would give rise to civil liability, or (4) depict or encourage profanity, nudity, inappropriate clothing, sexual acts, sexually suggestive poses or degrade or objectify people, whether in the nature of a prank, entertainment or otherwise.</li>

                    <li>You will not promote the use of explosives or firearms, the consumption of psychotropic drugs or any other illegal activities;</li>

                    <li>You will not disparage, make false or malicious statements against us or in connection with the Services or the Platform;</li>

                    <li>You will not interfere or attempt to interfere with the proper working of the Platform or any activities conducted on the Platform;</li>

                    <li>You will not bypass any measures we may use to prevent or restrict access to the Services;</li>

                    <li>You will not run any form of autoresponder or “spam” on the Platform;</li>

                    <li>You will not use manual or automated software, devices, or other processes to “crawl” or “spider” any part of the Services;</li>

                    <li>You will not modify, adapt, appropriate, reproduce, distribute, translate, create derivative works or adaptations of, publicly display, republish, repurpose, sell, trade, or in any way exploit the Service, except as expressly authorized by us;</li>

                    <li>You will not delete or modify any content of the Services, including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that you do not own or have express permission to modify</li>

                </ul>

                <h2>6) PAYMENT TERMS</h2>

                <p>You hereby acknowledge and agree that in order to avail our services; you explicitly agree to pay the fees in a manner and mode, as notified to you by us. The said fee is subject to a periodic review and may be revised at our sole discretion and such revisions may be intimated to you as and when required. Please note that your network operator may also separately charge you for data and other usage.</p>

                <h2>7) CANCELLATION AND REFUND POLICY</h2>

                <p>if you buy any Vaastu from the website for your use, if you find it in a broken state, then you will have to make a video of it (while opening) and send it to our email: support@satim.com, after which our assistant will check it. Will replace within 7 days
                    If you use our store or Vaastu delivery service, you are not allowed a refund or replacement.
                </p>

                <p>Regarding Guru Gyan, refund can be considered only in the following cases:</p>

                <p>Network problem due to which the chat/call gets affected during the service or due to factors like weak signal, background noise or inaudibility of the astrologer during the session.</p>
                <p> Guru Ji was unable to respond fluently in the language given in the profile</p>
                <p>Guruji was taking excessive time to respond to the user.</p>
                <p>Guruji has provided an irrelevant or inappropriate response to the user's question.</p>
                <p>No refund will be processed in the following cases</p>

                <p>The order has reached the processing stage i.e., a Guruji has already been appointed.</p>

                <p>The Platform may face technical delays or glitches in processing the request or generating the report from Guruji.</p>
                <p>The information given by you is wrong. You agree to verify any information you submit to the Platform and ensure that any such information is accurate. If the information provided is incorrect, you may request for correction of the information, provided such request is made within 1 (one) hour of the service provided by Guruji.</p>

                <p>The contact number provided by you for the purpose of availing Guruji is incorrect. Once you choose to avail the call with the astrologer, you are requested to ensure that your contact number is available within the coverage area and that you answer the call when it comes.</p>

                <p>Wrong results from consultation. Please note that we do not take responsibility for the factual accuracy of the results arising from the service provided</p>

                <p>Refunds, if any, will be processed after deducting transaction fees charged by the Bank and/or Payment Gateway and/or any other charges incurred by the Platform during processing and/or providing the Service, as applicable</p>

                <h2>8) CONDITIONS TO USE</h2>

                <ul>
                    <li>The Services will be provided on a best-efforts basis. We will make reasonable efforts and shall endeavor that you are able to use the Services without undue disruption, interruption or delay</li>

                    <li>Once you login on the Platform, you may receive updates, promotional materials and other information we may send with regards to the Service, or new services we may offer. You hereby consent to receiving all such commercial communications from us. You may opt out of receiving any, or all, of these commercial communications by writing to us at legal@satimt.com.</li>
                    <li>By agreeing to these Terms of Use, you also hereby unconditionally consent to us arranging a call with you on your mobile number although such number may be availing the DND service provided by your mobile service provider</li>
                    <li>We disclaim any responsibility for any harm resulting from anyone’s use of or access to the Services. If you avail our Services, you are responsible for taking precautions as necessary to protect yourself and your device (s) from malware, viruses, spyware, trojan horses, worms or trap doors, and other such harmful or destructive software.</li>

                    <li>We disclaim any responsibility for any harm resulting from anyone’s use of or access to the Services. If you avail our Services, you are responsible for taking precautions as necessary to protect yourself and your device (s) from malware, viruses, spyware, trojan horses, worms or trap doors, and other such harmful or destructive software. You also agree that we shall not be liable to you for any damages that may result from your use and/or misuse of our Platform.</li>
                </ul>

                <h2>9)	INTELLECTUAL PROPERTY</h2>
                <p>You agree and acknowledge that we are and we will remain the owner of the Platform and the Services thereunder at all times. You acknowledge that copyright in works contained on the Platform and the Services, including but not limited to all the features, functionality software, design, text, sound recordings and images, are our exclusive property, or licensed by us, except as otherwise expressly stated. You may access the Platform as a bona fide visitor or only for your use of the Services offered.</p>
                <p> All trademarks, service marks, trade names, trade dress, and other forms of intellectual property are proprietary to us. No information, code, algorithms, content or material from the Platform or the Services may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way without our express written permission.</p>

                <h2>10)	THIRD-PARTY LINKS</h2>

                <p>The Platform includes links to third-party websites and/or applications. You acknowledge that when you access a third-party link that leaves the Platform:</p>

                <p>the website or application you enter into is not controlled by the Company and different terms of use and privacy policies may apply;</p>

                <p> the inclusion of a link does not imply any endorsement by the Company of the third-party website and/or application, the website’s and/or application’s provider, or the information on the third-party website and/or application; and</p>

                <p> if you submit any information or details on any of those websites and/or applications, such information is governed by the terms of use and privacy policies of such third-party websites and/or applications and the Company disclaims all responsibility or liability with respect to these terms of use, policies or the websites and/or applications</p>

                <p> You are encouraged to carefully read the terms of use and privacy policy of any third-party website and/or application that you visit. The Company reserves the right to disable third-party links from the Platform, although the Company is under no obligation to do so.</p>

                <h2> 11)	INDEMNITY AND LIMITATION OF LIABILITY</h2>

                <p>To the extent permitted by law, you agree to indemnify the Company, its officers, directors and employees from and against any losses, damages, costs, expenses and claims arising out of (1) your use of the Services; (2) any breach of these Terms of Use or Privacy Policy by you; (3) any infringement of any intellectual property or other rights of the Company or any third- party or (4) your breach of any applicable laws.</p>

                <p>To the fullest extent permitted by law, in no event will the Company or its affiliates be liable in respect of the Platform and/or the Services for any direct, indirect, special, incidental, punitive, exemplary or consequential damages whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not the Company has been warned of the possibility of such damages. You expressly understand that under no circumstances, including negligence, will the Company be liable to you or any other person or entity for any direct, indirect, incidental, special, remote or consequential damages, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses, resulting from circumstances, including with respect to:</p>

                <p>the use or the inability to use the Platform and/or the Services;</p>

                <p> your reliance on the statements or claims made by us in the course of rendering our Services; or</p>

                <p>any other matter relating to the Platform and/or Services.
                Additionally, by using the Platform or any of the Services, you acknowledge and agree that internet transmissions are never completely private or secure. You understand that any message or information you send using the Platform or any of the Services may be read or intercepted by others, even if there is a special notice that a particular transmission is encrypted.</p>

                <h2>12)	 RIGHTS & RESERVATIONS</h2>

                <p>To the extent permitted by law, you agree to indemnify the Company, its officers, directors and employees from and against any losses, damages, costs, expenses and claims arising out of (1) your use of the Services; (2) any breach of these Terms of Use or Privacy Policy by you; (3) any infringement of any intellectual property or other rights of the Company or any third- party or (4) your breach of any applicable laws.</p>

                <p>To the fullest extent permitted by law, in no event will the Company or its affiliates be liable in respect of the Platform and/or the Services for any direct, indirect, special, incidental, punitive, exemplary or consequential damages whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not the Company has been warned of the possibility of such damages. You expressly understand that under no circumstances, including negligence, will the Company be liable to you or any other person or entity for any direct, indirect, incidental, special, remote or consequential damages, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses, resulting from circumstances, including with respect to:</p>

                <p> the use or the inability to use the Platform and/or the Services;</p>
                <p> your reliance on the statements or claims made by us in the course of rendering our Services; or</p>
                <p>Make all decisions in relation to inter alia your registration with SelectAstro;
                Request additional documents and additional information from you for the purpose of your registration as a User with the website; and
                Deny access to the App/ Web or any portion thereof without notice for the following reasons (i) any unauthorized access or use by you; (ii) attempt(s) to assign or transfer any rights granted to you under this EULA; and/or (iii) violation of any of the provisions of this EULA or any Applicable Laws..
                </p>

                <h2>13)	TERMINATION</h2>

                <p>We may terminate your access to all or any part of the Service at any time, with or without cause, with or without notice, effective immediately. Any suspected illegal, fraudulent or abusive activity will also be grounds for terminating your access to the Platform and/or Services.</p>
                <p>13.2. We reserve the right to, at our sole discretion, (a) cease operating the Platform or any of the Services at any time without notice, and/or (b) terminate these Terms of Use.</p>
                <p>13.3. All provisions of these Terms of Use which by their nature survive termination shall survive termination, including, without limitation, intellectual property (Clause 9), indemnity and limitation of liability (Clause 11) and disclaimer (Clause 14).</p>

                <h2>14)	DISCLAIMER</h2>

                <p>We hereby expressly state that the Services provided on the Platform are solely in relation to the Sanatana Dharma. You hereby agree and acknowledge that such restriction of Services to the Sanatana Dharma is in no manner discriminatory towards other religions or religious practices and shall not, under any circumstances whatsoever be deemed to be a disrespect of other religions or be deemed as favouring of Sanatana Dharma over other religions or religious practices.</p>
                <p>14.2. We do not in any manner represent or warrant nor do we undertake any responsibility or liability about the reality or reliability of the astrological effects on human physiology or any other products or services represented and sold on the Platform. No advice or information, whether oral or written, obtained by you through the Platform while availing the Services (including from any third-party service provider) shall create any warranty by the Company. We do not encourage or tolerate any content that promotes actions involving black magic, witchcraft, voodoo or tantrism in any manner. We do not commit to treating or providing solutions for users experiencing weak physical and/or mental health nor do we provide any medical advice. Users are advised to seek appropriate medical advice for any issues relating to physical or mental health.</p>
                <p>14.3. The advisors/consultants/guru are not employees of the Platform or the Company and are third party service providers. You agree and acknowledge that you are connecting with third party service providers at your own risk, and we undertake no responsibility or liability with respect to such third-party service providers. We do not refer, endorse, recommend, verify, evaluate or guarantee any advice, information or other services provided by the third-party service providers or by the Company, nor do we warrant the validity, accuracy, completeness, safety, legality, quality, or applicability of the content, anything said or written by, or any advice provided by such third-party service providers. You further agree that in no event will we be made a party to or have any liability with respect to any dispute between you and any third-party service provider. We may terminate the services of any third-party service provider at any time and without any liability, at our sole discretion.</p>
                <p>14.4. Save to the extent required by law, we have no special relationship with or fiduciary duty to you. You acknowledge that we have no control over, and no duty to take any action regarding the effects the Services may have on you.</p>
                <p>14.5. You agree and acknowledge that the Services are provided on an “as is” basis, and that we hereby do not guarantee or warrant to the accuracy, adequacy, correctness, validity, completeness, or suitability for any purpose, of the Services and accept no liability or responsibility with respect to your reliance on the statements or claims made by us in the course of rendering our Services.</p>
                <p>14.6. The Company makes no representation or warranty that the content on the Platform is appropriate to be used or accessed outside the Republic of India. Any users who use or access the Platform or avail the Services from outside the Republic of India, do so at their own risk and are responsible for compliance with the laws of such jurisdiction.</p>
                <h2>15)  GOVERNING LAW</h2>
                <p>15.1. A printed version of these Terms of Use and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms of Use to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
                <p>15.2. These Terms of Use shall be governed by and construed in accordance with the laws of India. For all purposes of these Terms of Use, you consent to the exclusive jurisdiction of the courts located in Bangalore, India. Use of the Service is not authorized in any jurisdiction that does not give effect to all provisions of these Terms of Use, including without limitation, this section.</p>
                <h2>16)	 SEVERABILITY</h2>
                <p>If any provision of these Terms of Use is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms of Use will otherwise remain in full force and effect and enforceable. The failure of either party to exercise, in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. Waiver of compliance in any particular instance does not mean that we will waive compliance in the future. In order for any waiver of compliance with these Terms of Use to be binding, we must provide you with written notice of such waiver through one of our authorized representatives.</p>
                <h2>17)	SCHEMES AND REWARDS</h2>
                <p>from time to time, satim may offer and rewards to you for inviting new users to the App/ Web and for completing other activities as per the terms and conditions indicated by SelectAstro to you.</p>
                <h2>18)	REPRESENTATIONS</h2>
                <p>From time to time, SATIM may offer and rewards to you for inviting new users to the App/ Web and for completing other activities as per the terms and conditions indicated by SATIM to you.</p>
                <h2>19)	MODIFICATION OF TERMS OF USE</h2>
                <p>We reserve the right, at our sole discretion, to modify or replace any of these Terms of Use, or change, suspend, or discontinue the Services (including without limitation, the availability of any feature, database, or content) or its usage at any time by posting a notice or by sending you notice through our Service or via email/contact details provided as Login Details. We may also impose limits on certain features and services or restrict your access to parts or all of the Services without notice or liability. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Services following the posting of any changes to these Terms of Use shall constitute an acceptance of those changes.</p>
                <h2>20)	MISCELLANEOUS</h2>
                <p>20.1. Unless otherwise specified in these Terms of Use, all notices hereunder will be in writing and will be deemed to have been duly given when received or when receipt is electronically confirmed, if transmitted by e-mail.</p>
                <p>20.2. In respect of these Terms of Use and your use of these Services, nothing in these Terms of Use shall be deemed to grant any rights or benefits to any person, other than us and you, or entitle any third party to enforce any provision hereof, and it is agreed that we do not intend that any provision of these Terms of Use should be enforceable by a third party as per any applicable law.</p>
                <h2>21)	CONTACT</h2>
                <p>n the event that you wish to raise a query or complaint with us, please contact our Grievance Officer (contact details set out below) who shall acknowledge your complaint within 24 (twenty four) hours from the time of receipt of such complaint. Kindly note that once your complaint is received, we shall use our best efforts to redress it within a period of 15 (fifteen) days from the date of receipt of such complaint:</p>
                <p>Email ID: legal@satim.com</p>
                <p>YOU HAVE FULLY READ AND UNDERSTOOD THESE TERMS OF USE AND </p>
                <p>VOLUNTARILY AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE</p>
                <p>Last updated on 1th May 2024</p>






            </div>

        </div>

    )
}

export default TermsCondition
