const countryCodes = [
    { name: "Afghanistan", dial_code: "+93", code: "AF", emoji: "🇦🇫" },
    { name: "Albania", dial_code: "+355", code: "AL", emoji: "🇦🇱" },
    { name: "Algeria", dial_code: "+213", code: "DZ", emoji: "🇩🇿" },
    { name: "Andorra", dial_code: "+376", code: "AD", emoji: "🇦🇩" },
    { name: "Angola", dial_code: "+244", code: "AO", emoji: "🇦🇴" },
    { name: "Argentina", dial_code: "+54", code: "AR", emoji: "🇦🇷" },
    { name: "Armenia", dial_code: "+374", code: "AM", emoji: "🇦🇲" },
    { name: "Australia", dial_code: "+61", code: "AU", emoji: "🇦🇺" },
    { name: "Austria", dial_code: "+43", code: "AT", emoji: "🇦🇹" },
    { name: "Azerbaijan", dial_code: "+994", code: "AZ", emoji: "🇦🇿" },
    { name: "Bahrain", dial_code: "+973", code: "BH", emoji: "🇧🇭" },
    { name: "Bangladesh", dial_code: "+880", code: "BD", emoji: "🇧🇩" },
    { name: "Belarus", dial_code: "+375", code: "BY", emoji: "🇧🇾" },
    { name: "Belgium", dial_code: "+32", code: "BE", emoji: "🇧🇪" },
    { name: "Bhutan", dial_code: "+975", code: "BT", emoji: "🇧🇹" },
    { name: "Brazil", dial_code: "+55", code: "BR", emoji: "🇧🇷" },
    { name: "Canada", dial_code: "+1", code: "CA", emoji: "🇨🇦" },
    { name: "China", dial_code: "+86", code: "CN", emoji: "🇨🇳" },
    { name: "Denmark", dial_code: "+45", code: "DK", emoji: "🇩🇰" },
    { name: "Egypt", dial_code: "+20", code: "EG", emoji: "🇪🇬" },
    { name: "France", dial_code: "+33", code: "FR", emoji: "🇫🇷" },
    { name: "Germany", dial_code: "+49", code: "DE", emoji: "🇩🇪" },
    { name: "India", dial_code: "+91", code: "IN", emoji: "🇮🇳" },
    { name: "Indonesia", dial_code: "+62", code: "ID", emoji: "🇮🇩" },
    { name: "Iran", dial_code: "+98", code: "IR", emoji: "🇮🇷" },
    { name: "Iraq", dial_code: "+964", code: "IQ", emoji: "🇮🇶" },
    { name: "Ireland", dial_code: "+353", code: "IE", emoji: "🇮🇪" },
    { name: "Italy", dial_code: "+39", code: "IT", emoji: "🇮🇹" },
    { name: "Japan", dial_code: "+81", code: "JP", emoji: "🇯🇵" },
    { name: "Kenya", dial_code: "+254", code: "KE", emoji: "🇰🇪" },
    { name: "Malaysia", dial_code: "+60", code: "MY", emoji: "🇲🇾" },
    { name: "Mexico", dial_code: "+52", code: "MX", emoji: "🇲🇽" },
    { name: "Nepal", dial_code: "+977", code: "NP", emoji: "🇳🇵" },
    { name: "Netherlands", dial_code: "+31", code: "NL", emoji: "🇳🇱" },
    { name: "New Zealand", dial_code: "+64", code: "NZ", emoji: "🇳🇿" },
    { name: "Nigeria", dial_code: "+234", code: "NG", emoji: "🇳🇬" },
    { name: "Norway", dial_code: "+47", code: "NO", emoji: "🇳🇴" },
    { name: "Pakistan", dial_code: "+92", code: "PK", emoji: "🇵🇰" },
    { name: "Philippines", dial_code: "+63", code: "PH", emoji: "🇵🇭" },
    { name: "Poland", dial_code: "+48", code: "PL", emoji: "🇵🇱" },
    { name: "Portugal", dial_code: "+351", code: "PT", emoji: "🇵🇹" },
    { name: "Qatar", dial_code: "+974", code: "QA", emoji: "🇶🇦" },
    { name: "Russia", dial_code: "+7", code: "RU", emoji: "🇷🇺" },
    { name: "Saudi Arabia", dial_code: "+966", code: "SA", emoji: "🇸🇦" },
    { name: "Singapore", dial_code: "+65", code: "SG", emoji: "🇸🇬" },
    { name: "South Africa", dial_code: "+27", code: "ZA", emoji: "🇿🇦" },
    { name: "South Korea", dial_code: "+82", code: "KR", emoji: "🇰🇷" },
    { name: "Spain", dial_code: "+34", code: "ES", emoji: "🇪🇸" },
    { name: "Sri Lanka", dial_code: "+94", code: "LK", emoji: "🇱🇰" },
    { name: "Sweden", dial_code: "+46", code: "SE", emoji: "🇸🇪" },
    { name: "Switzerland", dial_code: "+41", code: "CH", emoji: "🇨🇭" },
    { name: "Thailand", dial_code: "+66", code: "TH", emoji: "🇹🇭" },
    { name: "Turkey", dial_code: "+90", code: "TR", emoji: "🇹🇷" },
    { name: "United Arab Emirates", dial_code: "+971", code: "AE", emoji: "🇦🇪" },
    { name: "UK", dial_code: "+44", code: "GB", emoji: "🇬🇧" },
    { name: "USA", dial_code: "+1", code: "US", emoji: "🇺🇸" },
    { name: "Vietnam", dial_code: "+84", code: "VN", emoji: "🇻🇳" },
  ].sort((a, b) => a.name.localeCompare(b.name));
  
  export default countryCodes;
  